# Плагин разработан Денисом Тимофеевым.
#
# ВК - @M0odi
# Telegram - @ByNiX
# Discord - 𝙆𝙖𝙢𝙞𝙣𝙖#6102
#

# m0odi-chest.row-4                   Пермишны для возможности игрокам
# m0odi-chest.row-5                   приобретать данные строки.
# m0odi-chest.row-6                   (Если у игрока не будет пермишна на покупку 4 строки,
#                                     купить ее, соответственно, он не сможет)

# m0odi-chest.enderchest              Право на открытие виртуального Эндер Сундука.
# m0odi-chest.enderchest.other        Право на открытие чужого виртуального Эндер Сундука.
# m0odi-chest.enderchest.other.admin  Право на взаимодействие с чужим Эндер Сундуком

title-chest: "&0Эндер-Сундук"

prices: # Стоимости строк.
  row-4: 30
  row-5: 50
  row-6: 80

items:

  # Айтемы, которые будет отображаться на 4, 5, 6 строках кастомного
  # Эндер Сундука если они не приобретены.
  # Даты, зачарования, скрытие атрибутов и прочая поебота - не поддерживаются.

  row-4-item:
    material: red_stained_glass_pane
    amount: 1
    display-name: "&4&l❌ &7Не приобретено"
    lore:
      - "&7Приобретите эту строку за &c30 &7монет"
      - "&7[&cКЛИК&7] - купить строку"

  row-5-item:
    material: red_stained_glass_pane
    amount: 1
    display-name: "&4&l❌ &7Не приобретено"
    lore:
      - "&7Приобретите эту строку за &c50 &7монет"
      - "&7[&cКЛИК&7] - купить строку"

  row-6-item:
    material: red_stained_glass_pane
    amount: 1
    display-name: "&4&l❌ &7Не приобретено"
    lore:
      - "&7Приобретите эту строку за &c80 &7монет"
      - "&7[&cКЛИК&7] - купить строку"

  # Айтем, который будет отображаться для
  # просьбы подтвердить покупку.
  confirm-item:
    material: orange_stained_glass_pane
    amount: 1
    display-name: "&7[&6&l!&7] &7Подтвердите покупку"
    lore:
      - "&7Подтвердите покупку строки"
      - "&7[&cКЛИК&7] - подтвердить"

messages:
  not-perms: "&7У вас нет прав для исполнения этой команды"

  not-perm-row-4: "&7У вас нет прав для покупки 4-й строчки"
  not-perm-row-5: "&7У вас нет прав для покупки 5-й строчки"
  not-perm-row-6: "&7У вас нет прав для покупки 6-й строчки"

  not-enough-money: "&7Недостаточно монет для покупки"

  not-have-previous: "&7Для покупки этой строки Вам необходимо приобрести все предыдущие строки"

  bought-row: "&7Вы приобрели новую строчку"

